name: unit test script
on:
    push
jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v6
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v7
        - name: install project dependencies
          run: uv sync --dev
        - name: run tests
          run: uv run python -m pytest tests
